### ISSUE TITLE
upload of XLS form with many questions (413 error)

### ISSUE THREAD

**Issue by raeesaroj** [fieldsight/fieldsight#10]

**Comment by raeesaroj** [comment]
As I found a solution, we can add 
`client_max_body_size 100M;`
in nginx server block. So that user can upload a file of max size 100M.

**Comment by awemulya** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [issue regarding upload error. (kpi xls upload error)](https://trello.com/c/APflj4ut/192-issue-regarding-upload-error-kpi-xls-upload-error)
