### ISSUE TITLE
IntegrityError: duplicate key value violates unique constraint "fcm_device_reg_id_key"

### ISSUE THREAD

**Issue by santoshkhatrii** [fieldsight/fieldsight#103]
[Trello Link](https://trello.com/c/QEJok3kE)

**Comment by raeesaroj** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [IntegrityError: duplicate key value violates unique constraint "fcm_device_reg_id_key"](https://trello.com/c/QEJok3kE/424-integrityerror-duplicate-key-value-violates-unique-constraint-fcmdeviceregidkey)
