### ISSUE TITLE
deleted submissions appearing in excel download.

### ISSUE THREAD

**Issue by raeesaroj** [fieldsight/fieldsight#23]
This is because excel sheet is generated from mongo database and https://github.com/fieldsight/fieldsight/blob/master/onadata/apps/fsforms/management/commands/create_mongo_instance.py have created, deleted submissions in mongo.

**Comment by awemulya** [comment]
This was causing some sleepless nights for me. I was always wondering why users complain about excell sheet submissions.
create_mongo_instance should not create deleted submissions.
update deleted_at to mongo for deleted Finstances.

**Comment by awemulya** [comment]
set deleted flag on deleted submissions.
