### ISSUE TITLE
Handle multiple versions key in submission xml

### ISSUE THREAD

**Issue by SanipRijal** [fieldsight/fieldsight#25]
While downloading XLS of the form from KPI, the file has " version " as calculate field. This is the form version.
When the edited excel form is uploaded to KPI using replace with XLS, the calculate field " version " is added as a question in the question set. If the form is again downloaded, there is another " version " as calculate field. Uploading this leads to another question in the form. This happens every time replacement is done.

**Comment by awemulya** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [multiple versions key in submission xml.](https://trello.com/c/AMzSNj5H/125-multiple-versions-key-in-submission-xml)
