### ISSUE TITLE
Problem accessing the dashboard

### ISSUE THREAD

**Issue by marceloscarone** [fieldsight/fieldsight#366]
When you enter the dashboard page, the page is blank. https://app.fieldsight.org/fieldsight/application/#/project-dashboard/406
![video-error-dashboard](https://user-images.githubusercontent.com/50563569/67520042-7b82e980-f67e-11e9-9264-629ea3c77550.gif)

**Comment by awemulya** [comment]
Thanks for reporting @marceloscarone  its resolved now.
