### ISSUE TITLE
Error editing forms

### ISSUE THREAD

**Issue by marceloscarone** [fieldsight/fieldsight#389]
When editing forms in the web application, after submitting, the form is not updated and the data is the same as before editing.

**Comment by awemulya** [comment]
@marceloscarone This issue is form specific. (seen in some forms with version changed)
It would be better If you could provide us form url.

**Comment by marceloscarone** [comment]
https://app.fieldsight.org/fieldsight/application/?submission=310423#/submission-details

I've tried again and now yes, the changes have been made. I think the problem is solved
