### ISSUE TITLE
Error creating forms

### ISSUE THREAD

**Issue by marceloscarone** [fieldsight/fieldsight#425]
It is not possible to create forms, or even edit existing ones, from https://kpi.fieldsight.org/#/forms/a9qx2ya3CrEMYqc5Jsczoi/edit/.
Since kobotoolbox we do not have this problem, we have a good internet connection.
![ERROR CREATING FORM](https://user-images.githubusercontent.com/50563569/75358511-c497b400-5891-11ea-9899-3fb3eca30f75.PNG)

**Comment by marceloscarone** [comment]
Works from other browser (mozilla)

**Comment by awemulya** [comment]
https://github.com/fieldsight/fieldsight/pull/426
fixed.
