### ISSUE TITLE
Bulk Upload Sites gives "Could not convert string to float"

### ISSUE THREAD

**Issue by marceloscarone** [fieldsight/fieldsight#427]
![bulk error](https://user-images.githubusercontent.com/50563569/75489868-d3fe2680-5991-11ea-9df3-54d83e28f413.PNG)
[bulk_upload_sites (9).xlsx](https://github.com/fieldsight/fieldsight/files/4264247/bulk_upload_sites.9.xlsx)

**Comment by awemulya** [comment]
There is invalid data in excel sheet.
decimal column containing non float data.
