### ISSUE TITLE
delete all roles, submission ids while deleting site.

### ISSUE THREAD

**Issue by raeesaroj** [fieldsight/fieldsight#51]

**Comment by awemulya** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Submissions for deleted sites are being exported in the form data export (kobo) with blank site name and address.](https://trello.com/c/JKAOTjyO/323-submissions-for-deleted-sites-are-being-exported-in-the-form-data-export-kobo-with-blank-site-name-and-address)
