### ISSUE TITLE
Form Assignment to project

### ISSUE THREAD

**Issue by hereyubaraj** [fieldsight/fieldsight#61]
It is very hard to find the form if it has large form list. Better would be if we add the search input field just below the select form.

<img width="1428" alt="screenshot 2019-02-26 14 33 47" src="https://user-images.githubusercontent.com/47551530/53399343-edae0c00-39d3-11e9-803a-85f77fa54696.png">

**Comment by awemulya** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [While assigning a new form, that has already been deleted under General Form/Scheduled form or Survey forms, an error message is displayed.](https://trello.com/c/mJnoGgxi/309-while-assigning-a-new-form-that-has-already-been-deleted-under-general-form-scheduled-form-or-survey-forms-an-error-message-is-d)

**Comment by awemulya** [comment]
This is a feature of fieldsight not a bug.

**Comment by awemulya** [comment]
Form UI enhancement
