### ISSUE TITLE
Internal Server Error: /project-notify/<id>

### ISSUE THREAD

**Issue by raeesaroj** [fieldsight/fieldsight#68]

**Comment by raeesaroj** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Internal Server Error: /project-notify/<id>](https://trello.com/c/vJJpQKxd/351-internal-server-error-project-notify-id)

**Comment by awemulya** [comment]
Lookes linke notification server not working/ or nginx dir to notification not correct.
