### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcd in position 245: ordinal not in range(128)

### ISSUE THREAD

**Issue by santoshkhatrii** [fieldsight/fieldsight#90]
https://trello.com/c/YyDAQQF2

**Comment by awemulya** [comment]
https://github.com/kobotoolbox/kobocat/issues/289

**Comment by santoshkhatrii** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [UnicodeDecodeError: 'ascii' codec can't decode byte 0xcd in position 245: ordinal not in range(128)](https://trello.com/c/YyDAQQF2/414-unicodedecodeerror-ascii-codec-cant-decode-byte-0xcd-in-position-245-ordinal-not-in-range128)

**Comment by awemulya** [comment]
Internal Server Error: /api/v1/forms/1257
Traceback (most recent call last):
  File "/kobocat/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/kobocat/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/kobocat/local/lib/python2.7/site-packages/rest_framework/viewsets.py", line 87, in view
    return self.dispatch(request, *args, **kwargs)
  File "/kobocat/local/lib/python2.7/site-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/kobocat/local/lib/python2.7/site-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/kobocat/local/lib/python2.7/site-packages/rest_framework/mixins.py", line 78, in partial_update
    return self.update(request, *args, **kwargs)
  File "./onadata/apps/api/viewsets/xform_viewset.py", line 800, in update
    survey = utils.publish_xlsform(request, owner, existing_xform)
  File "./onadata/apps/api/tools.py", line 264, in publish_xlsform
    return publish_form(set_form)
  File "./onadata/libs/utils/logger_tools.py", line 413, in publish_form
    if u"ODK Validate Errors" not in e.message:
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcd in position 245: ordinal not in range(128)

Request repr():
<WSGIRequest
path:/api/v1/forms/1257,
GET:<QueryDict: {}>,
POST:<QueryDict: {}>,
COOKIES:{},
META:{'CONTENT_LENGTH': '14193',
 'CONTENT_TYPE': 'multipart/form-data; boundary=7f9045ebd44041faa5b04472b392a025',
 u'CSRF_COOKIE': u'OrlHKiOtof8dGruYtYYrNIyOOOPC70O7',
 'DOCUMENT_ROOT': '/srv/fieldsight/kobocat',
 'HTTP_ACCEPT': '*/*',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate',
 'HTTP_AUTHORIZATION': 'Token edce6da94283e3ac6d2cc34c282e1cd6ca945d83',
 'HTTP_CONNECTION': 'keep-alive',
 'HTTP_CONTENT_LENGTH': '14193',
 'HTTP_CONTENT_TYPE': 'multipart/form-data; boundary=7f9045ebd44041faa5b04472b392a025',
 'HTTP_HOST': 'app.fieldsight.org',
 'HTTP_USER_AGENT': 'python-requests/2.10.0',
 'PATH_INFO': u'/api/v1/forms/1257',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '18.219.102.111',
 'REMOTE_PORT': '60752',
 'REQUEST_METHOD': 'PATCH',
 'REQUEST_SCHEME': 'http',
 'REQUEST_URI': '/api/v1/forms/1257',
 u'SCRIPT_NAME': u'',
 'SERVER_NAME': 'app.fieldsight.org',
 'SERVER_PORT': '80',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'uwsgi.core': 1,
 'uwsgi.node': 'ip-172-31-1-162',
 'uwsgi.version': '2.0.15',
 'wsgi.errors': <open file 'wsgi_errors', mode 'w' at 0x7f9513290db0>,
 'wsgi.file_wrapper': <built-in function uwsgi_sendfile>,
 'wsgi.input': <uwsgi._Input object at 0x7f94f6a7a768>,
 'wsgi.multiprocess': True,
 'wsgi.multithread': True,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}>

**Comment by awemulya** [comment]
https://community.kobotoolbox.org/t/ascii-codec-cant-decode-byte-0x2-in-position-2313-ordinal-not-in-range-128-contactkobotoolbox-support/354
