### ISSUE TITLE
Password Reset and Password Change UI enhancement

### ISSUE THREAD

**Issue by santoshkhatrii** [fieldsight/fieldsight#91]
Should resemble the UI in the signin/signup page.

https://trello.com/c/pBPUJuoa

**Comment by raeesaroj** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [UI Enhancement in Password Change and Password Reset pages.](https://trello.com/c/pBPUJuoa/415-ui-enhancement-in-password-change-and-password-reset-pages)
